'use strict'; // code generated by pbf v3.2.0

// Blob ========================================

var Blob = exports.Blob = {};

Blob.read = function (pbf, end) {
    return pbf.readFields(Blob._readField, {raw: null, raw_size: 0, zlib_data: null, lzma_data: null, OBSOLETE_bzip2_data: null}, end);
};
Blob._readField = function (tag, obj, pbf) {
    switch(tag) {
    case 1: obj.raw = pbf.readBytes(); break;
    case 2: obj.raw_size = pbf.readVarint(true); break;
    case 3: obj.zlib_data = pbf.readBytes(); break;
    case 4: obj.lzma_data = pbf.readBytes(); break;
    case 5: obj.OBSOLETE_bzip2_data = pbf.readBytes(); break;
    }
};

// BlobHeader ========================================

var BlobHeader = exports.BlobHeader = {};

BlobHeader.read = function (pbf, end) {
    return pbf.readFields(BlobHeader._readField, {type: "", indexdata: null, datasize: 0}, end);
};
BlobHeader._readField = function (tag, obj, pbf) {
    switch(tag) {
    case 1: obj.type = pbf.readString(); break;
    case 2: obj.indexdata = pbf.readBytes(); break;
    case 3: obj.datasize = pbf.readVarint(true); break;
    }
};
